// ... existing code ...
const API_CONFIG = {
  BASE_URL: 'https://blockchain-voting-system-backend.onrender.com',
  ENDPOINTS: {
    NONCE: '/api/nonce',
    VERIFY: '/api/verify',
    // ... keep other endpoints the same ...
  },
  // ... existing code ...
};
// ... existing code ...